#!/bin/bash
# ============================================
# 🚀 GUIDE DE DÉMARRAGE RAPIDE
# ============================================

echo "╔════════════════════════════════════════════════════════════╗"
echo "║     ✅ WhatsApp Groq Bot v2.0 PRO - Prêt à l'emploi!      ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "📦 FICHIERS CRÉÉS:"
echo "  ✅ src/config.js         - Configuration centralisée"
echo "  ✅ src/logger.js         - Logging structuré"
echo "  ✅ src/database.js       - Wrapper SQLite3 sécurisé"
echo "  ✅ src/rateLimiter.js    - Protection spam"
echo "  ✅ src/services.js       - Services métier"
echo "  ✅ bot.js                - Bot principal (fusionné & amélioré)"
echo "  ✅ .env                  - Configuration locale"
echo "  ✅ .env.example          - Template config"
echo "  ✅ .gitignore            - Sécurité git"
echo "  ✅ test.js               - Tests unitaires"
echo "  ✅ install.sh            - Installation auto"
echo "  ✅ README.md             - Documentation"
echo "  ✅ IMPROVEMENTS.md       - Détail des améliorations"
echo "  ✅ DEPLOYMENT.md         - Guide production"
echo ""

echo "📊 AMÉLIORATIONS:"
echo "  ✅ Sécurité renforcée (sanitization, validation)"
echo "  ✅ Rate limiting (10 req/h par user)"
echo "  ✅ Logging structuré (4 niveaux + fichiers)"
echo "  ✅ Reconnexion automatique (exponential backoff)"
echo "  ✅ Gestion erreurs complète"
echo "  ✅ Database optimisée (indexes, migrations)"
echo "  ✅ Tests unitaires inclus"
echo "  ✅ Production-ready"
echo ""

echo "🚀 DÉMARRAGE RAPIDE:"
echo ""
echo "1️⃣  ÉDITER LA CONFIGURATION:"
echo "    nano .env"
echo "    → Remplacer GROQ_API_KEY=gsk_xxx par votre vraie clé"
echo ""
echo "2️⃣  VÉRIFIER LES PARAMÈTRES:"
echo "    npm run test"
echo "    → Doit afficher: ✅ TOUS LES TESTS RÉUSSIS!"
echo ""
echo "3️⃣  DÉMARRER LE BOT:"
echo "    ./control.sh start"
echo "    → Scanner le QR code avec WhatsApp"
echo ""
echo "4️⃣  VÉRIFIER LE STATUT:"
echo "    ./control.sh status"
echo "    → Doit afficher: ✅ Bot en cours d'exécution"
echo ""
echo "5️⃣  VOIR LES LOGS:"
echo "    ./control.sh logs"
echo "    → Affiche les logs en direct"
echo ""

echo "📚 COMMANDES UTILES:"
echo "  ./control.sh start         - Démarrer le bot"
echo "  ./control.sh stop          - Arrêter le bot"
echo "  ./control.sh restart       - Redémarrer"
echo "  ./control.sh status        - Vérifier l'état"
echo "  ./control.sh logs          - Logs en direct"
echo "  ./control.sh logs-error    - Erreurs uniquement"
echo "  ./control.sh clean         - Nettoyer session"
echo "  npm run test               - Tests"
echo "  npm run dev                - Dev mode"
echo ""

echo "🔧 CONFIGURATION (.env):"
echo "  GROQ_API_KEY               - Clé API Groq (OBLIGATOIRE)"
echo "  MY_NAME                    - Votre nom (défaut: Malkym)"
echo "  MY_PHONE                   - Votre numéro (+code pays)"
echo "  ABSENCE_START              - Heure début absence (20:00)"
echo "  ABSENCE_END                - Heure fin absence (08:00)"
echo "  LOG_LEVEL                  - info/debug/warn/error"
echo "  DEMO_MODE                  - true/false (toujours répondre)"
echo ""

echo "📂 FICHIERS IMPORTANTS:"
echo "  .env                       - ⚠️ NE PAS COMMITTER!"
echo "  conversations.db           - Base de données SQLite"
echo "  logs/                      - Dossier des logs"
echo "  wwebjs_auth/session        - Session WhatsApp"
echo ""

echo "🔐 SÉCURITÉ:"
echo "  ✅ GROQ_API_KEY dans .env (jamais committé)"
echo "  ✅ .gitignore complète"
echo "  ✅ Messages sanitizés"
echo "  ✅ Rate limiting actif"
echo "  ✅ Validation entrée"
echo ""

echo "❓ BESOIN D'AIDE?"
echo "  📖 README.md           - Guide complet"
echo "  🚀 DEPLOYMENT.md       - Production"
echo "  📋 IMPROVEMENTS.md     - Améliorations"
echo "  🧪 test.js             - Exemples"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "✨ BOT PRÊT! Lancez: ./control.sh start"
echo "═══════════════════════════════════════════════════════════"
echo ""
